/**
 * word_templates.h — AUTO-GENERATED by voice_system.py
 * DO NOT EDIT MANUALLY
 *
 * System: AVR Voice Command Recognition
 * Features: 16
 * Words: 8
 * Max templates per word: 5
 * Total templates: 40
 *
 * Feature order:
 *   [0]  energy_mean        [8]  spectral_centroid
 *   [1]  energy_std         [9]  spectral_flatness
 *   [2]  zcr_mean           [10] energy_entropy
 *   [3]  zcr_std            [11] band_ratio_lo_hi
 *   [4]  band0_energy       [12] peak_energy_pos
 *   [5]  band1_energy       [13] attack_slope
 *   [6]  band2_energy       [14] zcr_energy_corr
 *   [7]  band3_energy       [15] spectral_rolloff
 */

#ifndef WORD_TEMPLATES_H
#define WORD_TEMPLATES_H

#include <avr/pgmspace.h>
#include <stdint.h>

#define N_WORDS        8
#define N_FEATURES     16
#define MAX_TEMPLATES  5

/* Number of templates stored for each word */
extern const uint8_t n_templates_per_word[N_WORDS] PROGMEM;

/* Templates stored in flash: [word][template_idx][feature] */
extern const float word_templates[N_WORDS][MAX_TEMPLATES][N_FEATURES] PROGMEM;

/* Feature normalization: mean and std from training set */
/* Used to normalize query features before classification   */
extern const float feature_mean[N_FEATURES] PROGMEM;
extern const float feature_std[N_FEATURES]  PROGMEM;

/* Word label strings */
extern const char* const word_labels[N_WORDS] PROGMEM;

#endif /* WORD_TEMPLATES_H */
